import { VideoContent, Article, NewsItem, Post, Profile } from '@/types';

export const mockVideos: VideoContent[] = [
  {
    id: '1',
    title: 'Fundamentals of Method Acting',
    source: 'Stella Adler Studio',
    duration: '15 min',
    level: 'foundations',
    category: 'Acting Technique',
    summary: 'Learn the core principles of method acting and how to apply emotional memory to your performances.',
    thumbnailUrl: '/placeholder.svg',
    videoUrl: 'https://example.com/video1',
  },
  {
    id: '2',
    title: 'Self-Tape Best Practices',
    source: 'Casting Networks',
    duration: '12 min',
    level: 'foundations',
    category: 'Auditions',
    summary: 'Master the technical and performance aspects of creating professional self-tape auditions.',
    thumbnailUrl: '/placeholder.svg',
    videoUrl: 'https://example.com/video2',
  },
  {
    id: '3',
    title: 'Advanced Scene Analysis',
    source: 'Yale School of Drama',
    duration: '25 min',
    level: 'advanced',
    category: 'Acting Technique',
    summary: 'Deep dive into script analysis, character objectives, and subtext interpretation.',
    thumbnailUrl: '/placeholder.svg',
    videoUrl: 'https://example.com/video3',
  },
];

export const mockArticles: Article[] = [
  {
    id: '1',
    title: 'Building Your Acting Resume: A Complete Guide',
    source: 'Backstage Magazine',
    summary: 'Essential tips for creating a professional acting resume that gets noticed by casting directors.',
    fullUrl: 'https://example.com/article1',
    category: 'Career Development',
    publishedAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'The Business Side of Acting: What Every Actor Should Know',
    source: 'The Hollywood Reporter',
    summary: 'Understanding contracts, agents, and the financial aspects of a professional acting career.',
    fullUrl: 'https://example.com/article2',
    category: 'Industry Knowledge',
    publishedAt: '2024-01-10',
  },
];

export const mockNews: NewsItem[] = [
  {
    id: '1',
    title: 'Major Studio Announces Open Casting Call for New Series',
    summary: 'Netflix is seeking diverse talent for upcoming drama series filming in Atlanta.',
    source: 'IMDb',
    url: 'https://example.com/news1',
    publishedAt: '2024-01-20',
    aiInsights: 'This represents a great opportunity for emerging actors, especially those willing to relocate to Atlanta.',
  },
  {
    id: '2',
    title: 'SAG-AFTRA Announces New Guidelines for Self-Tape Submissions',
    summary: 'Updated standards for self-tape quality and submission requirements.',
    source: 'Variety',
    url: 'https://example.com/news2',
    publishedAt: '2024-01-18',
    aiInsights: 'These new guidelines emphasize the importance of professional-quality self-tapes in the modern casting process.',
  },
];

export const mockPosts: Post[] = [
  {
    id: '1',
    userId: 'user1',
    authorName: 'Sarah Chen',
    authorHeadshot: '/placeholder.svg',
    type: 'reel',
    content: 'Just finished my new demo reel! Would love feedback from the community.',
    mediaUrl: '/placeholder.svg',
    likes: 12,
    comments: [
      {
        id: '1',
        userId: 'user2',
        authorName: 'Mike Rodriguez',
        content: 'Great work! The emotional range in the second scene is really compelling.',
        createdAt: '2024-01-19T10:30:00Z',
      },
    ],
    createdAt: '2024-01-19T09:00:00Z',
  },
  {
    id: '2',
    userId: 'user2',
    authorName: 'Mike Rodriguez',
    type: 'text',
    content: 'Looking for scene partners for a Meisner technique workshop this weekend. Anyone interested?',
    likes: 8,
    comments: [],
    createdAt: '2024-01-18T14:15:00Z',
  },
];

export const mockProfile: Profile = {
  id: '1',
  userId: 'user1',
  name: 'Sarah Chen',
  pronouns: 'she/her',
  ageRange: '25-30',
  location: 'Los Angeles, CA',
  willingToRelocate: true,
  height: '5\'6"',
  build: 'Athletic',
  eyeColor: 'Brown',
  hairColor: 'Black',
  ethnicity: 'Asian American',
  actingSchools: ['UCLA School of Theater'],
  workshops: ['Groundlings Improv', 'Stella Adler Technique'],
  coaches: ['Jane Smith Acting Coach'],
  stageExperience: true,
  filmExperience: true,
  specialSkills: ['Mandarin', 'Stage Combat', 'Piano'],
  unionStatus: 'SAG-AFTRA',
  preferredGenres: ['Drama', 'Comedy', 'Thriller'],
  careerGoals: 'To work in both independent films and television, focusing on complex character-driven stories.',
  headshots: ['/placeholder.svg'],
  resume: '/placeholder.pdf',
  demoReel: '/placeholder-video.mp4',
  socialLinks: ['@sarahchen_actor'],
  bio: 'Passionate actor with classical training and a focus on authentic storytelling.',
  tagline: 'Bringing depth and authenticity to every role',
  profileUrl: 'sarah-chen',
  isPublic: true,
  completionPercentage: 95,
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-19T00:00:00Z',
};